#!/usr/bin/bash

NAME=centos
if [ -f "./Dockerfile" ]; then NAME=.; fi

docker build -t vertx $NAME 

docker run -ti --privileged -p 8087:8087 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --name test_vertx vertx bash
