#!/usr/bin/bash

#debug production - see "build.gradle" for testing development
#Note; you can set VERTXWEB_ENVIRONMENT=dev to change the server port to development(8087)

java -DVERTXWEB_ENVIRONMENT=prod -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=5006,server=y,suspend=n -jar build/libs/dodex-vertx-3.8.4.jar 
