#!/usr/bin/bash

LIB=<dodex-vertx install>/build/install/dodex-vertx/lib
CD2=
for f in $LIB/*.jar
do
    CD2=$CD2$f:
done

native-image io.vertx.core.Launcher -jar <dodex-vertx install>/buils/libs/dodex-vertx-3.8.4.jar  -cp <dodex-vertx>/build/classes/java/main:$CD2 --initialize-at-build-time=org.slf4j,org.apache.commons.logging

