#!/usr/bin/bash
#####
# It appears the all graalvm dependencies are resolved from the location of native-image.
# So you can build the executable from the vertx directory. 
#
# Run "gradlew shadowJar" first
#####

~/work/graalvm-ce-java17-22.3.1/bin/native-image io.vertx.core.Launcher -jar ./build/libs/dodex-vertx-3.0.0-prod.jar  -cp ./build/classes/java/main --initialize-at-build-time=org.slf4j,org.apache.commons.logging -H:+ReportExceptionStackTraces
