#!/usr/bin/bash
#####
# It appears the all graalvm dependencies are resolved from the location of native-image.
# So you can build the executable from the vertx directory. Since dodex-vertx is a server
# a java vm(JAVA_HOME) is required to execute. 
#####
LIB=./build/install/dodex-vertx/lib
CD2=
for f in $LIB/*.jar
do
    CD2=$CD2$f:
done

<Install Location>/graalvm/bin/native-image io.vertx.core.Launcher -jar ./build/libs/dodex-vertx-3.8.4.jar  -cp ./build/classes/java/main:$CD2 --initialize-at-build-time=org.slf4j,org.apache.commons.logging --allow-incomplete-classpath --initialize-at-run-time=io.netty.handler.ssl.ConscryptAlpnSslEngine
