package dmo.fs.db.sqlite3;

import java.io.IOException;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

import dmo.fs.db.DbConfiguration;
import dmo.fs.db.MessageUser;
import dmo.fs.db.MessageUserImpl;
import dmo.fs.vertx.Server;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.JsonNode;
import dmo.fs.utils.DodexUtil;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.disposables.Disposable;
import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.jdbcclient.JDBCConnectOptions;
import io.vertx.rxjava3.jdbcclient.JDBCPool;
import io.vertx.rxjava3.sqlclient.Row;
import io.vertx.rxjava3.sqlclient.RowIterator;
import io.vertx.rxjava3.sqlclient.RowSet;
import io.vertx.sqlclient.PoolOptions;

public class DodexDatabaseSqlite3 extends DbSqlite3 {
  private final static Logger logger =
      LoggerFactory.getLogger(DodexDatabaseSqlite3.class.getName());
  protected Disposable disposable;
  protected Properties dbProperties = new Properties();
  protected Map<String, String> dbOverrideMap = new ConcurrentHashMap<>();
  protected Map<String, String> dbMap = new ConcurrentHashMap<>();
  protected JsonNode defaultNode;
  protected String webEnv = System.getenv("VERTXWEB_ENVIRONMENT");
  protected DodexUtil dodexUtil = new DodexUtil();
  protected Boolean isCreateTables = false;
  protected Promise<String> returnPromise = Promise.promise();

  public DodexDatabaseSqlite3(Map<String, String> dbOverrideMap, Properties dbOverrideProps)
      throws InterruptedException, IOException, SQLException {
    super();

    defaultNode = dodexUtil.getDefaultNode();

    webEnv = webEnv == null || "prod".equals(webEnv) ? "prod" : "dev";

    dbMap = dodexUtil.jsonNodeToMap(defaultNode, webEnv);
    dbProperties = dodexUtil.mapToProperties(dbMap);
    dbProperties.setProperty("foreign_keys", "true");

    if (dbOverrideProps != null && !dbOverrideProps.isEmpty()) {
      this.dbProperties = dbOverrideProps;
    }
    if (dbOverrideMap != null) {
      DbConfiguration.mapMerge(dbMap, dbOverrideMap);
      this.dbOverrideMap = dbOverrideMap;
    }

    databaseSetup();
  }

  public DodexDatabaseSqlite3() throws InterruptedException, IOException, SQLException {
    super();

    defaultNode = dodexUtil.getDefaultNode();
    webEnv = webEnv == null || "prod".equals(webEnv) ? "prod" : "dev";

    dbMap = dodexUtil.jsonNodeToMap(defaultNode, webEnv);
    dbProperties = dodexUtil.mapToProperties(dbMap);

    dbProperties.setProperty("foreign_keys", "true");

    databaseSetup();
  }

  public DodexDatabaseSqlite3(Boolean isCreateTables)
      throws IOException {
    super();
    defaultNode = dodexUtil.getDefaultNode();
    webEnv = webEnv == null || "prod".equals(webEnv) ? "prod" : "dev";

    dbMap = dodexUtil.jsonNodeToMap(defaultNode, webEnv);
    dbProperties = dodexUtil.mapToProperties(dbMap);

    dbProperties.setProperty("foreign_keys", "true");
    this.isCreateTables = isCreateTables;
  }

  public Future<String> checkOnTables() {
    databaseSetup();
    return returnPromise.future();
  }

  private void databaseSetup() {
    Promise<String> finalPromise = Promise.promise();
    if ("dev".equals(webEnv)) {
      DbConfiguration.configureTestDefaults(dbMap, dbProperties);
    } else {
      DbConfiguration.configureDefaults(dbMap, dbProperties); // Using prod (./dodex.db)
    }

    PoolOptions poolOptions =
        new PoolOptions().setMaxSize(5).setMaxWaitQueueSize(10)
            .setIdleTimeoutUnit(TimeUnit.MILLISECONDS).setIdleTimeout(3000);

    JDBCConnectOptions connectOptions;

    connectOptions = new JDBCConnectOptions()
        .setJdbcUrl(dbMap.get("url") + dbMap.get("filename") + "?foreign_keys=on;")
        .setAutoGeneratedKeys(true)
        .setIdleTimeout(1)
    // .setCachePreparedStatements(true)
    ;

    pool = JDBCPool.pool(Server.getRxVertx(), connectOptions, poolOptions);

    Completable completable = pool.rxGetConnection().flatMapCompletable(conn -> conn.rxBegin()
        .flatMapCompletable(tx -> conn.query(CHECKUSERSQL).rxExecute().doOnSuccess(row -> {
          RowIterator<Row> ri = row.iterator();
          String val = null;
          while (ri.hasNext()) {
            val = ri.next().getString(0);
          }

          if (val == null) {
            final String usersSql = getCreateTable("USERS");

            Single<RowSet<Row>> crow = conn.query(usersSql).rxExecute().doOnError(err -> {
              logger.error("Users Table Error: {}", err.getCause().getMessage());
            }).doOnSuccess(result -> {
              logger.warn("Users Table Added.");
            });

            crow.subscribe(result -> {
              //
            }, err -> {
              logger.warn("Returning Users Error: {}", err.getMessage());
            });
          }
        }).doOnError(err -> {
          logger.warn("Users Table Error: {}", err.getMessage());

        }).flatMap(result -> conn.query(CHECKMESSAGESSQL).rxExecute().doOnSuccess(row -> {
          RowIterator<Row> ri = row.iterator();
          String val = null;
          while (ri.hasNext()) {
            val = ri.next().getString(0);
          }

          if (val == null) {
            final String sql = getCreateTable("MESSAGES");

            Single<RowSet<Row>> crow = conn.query(sql).rxExecute().doOnError(err -> {
              logger.error("Returning Messages Error: {}", err.getMessage());
            }).doOnSuccess(row2 -> {
              logger.warn("Messages Table Added.");
            });

            crow.subscribe(res -> {
              //
            }, err -> {
              logger.error("Messages Table Error: {}", err.getMessage());
            });
          }
        }).doOnError(err -> {
          logger.error("Querying Messages Error: {}", err.getMessage());

        })).flatMap(result -> conn.query(CHECKUNDELIVEREDSQL).rxExecute().doOnSuccess(row -> {
          RowIterator<Row> ri = row.iterator();
          String val = null;
          while (ri.hasNext()) {
            val = ri.next().getString(0);
          }

          if (val == null) {
            final String sql = getCreateTable("UNDELIVERED");

            Single<RowSet<Row>> crow = conn.query(sql).rxExecute().doOnError(err -> {
              logger.error("Returning Undelivered Error: {}", err.getMessage());
            }).doOnSuccess(row2 -> {
              logger.warn("Undelivered Table Added.");
            });

            crow.subscribe(result2 -> {
              //
            }, err -> {
              logger.error("Undelivered Table Error: {}", err.getMessage());
            });
          }
        }).doOnError(err -> {
          logger.error("Querying Undelivered Error: {}", err.getMessage());
        })).flatMap(result -> conn.query(CHECKHANDICAPSQL).rxExecute().doOnError(err -> {
          logger.error("Golfer Exists Error: {}", err.getMessage());
        }).doOnSuccess(rows -> {
          Set<String> names = new HashSet<>();

          for (Row row : rows) {
            names.add(row.getString(0));
          }
          conn.query(getCreateTable("GOLFER")).rxExecute().doOnError(err -> {
            logger.error("Golfer Table Error: {}", err.getMessage());
          }).doOnSuccess(row1 -> {
            if (!names.contains("golfer")) {
              logger.warn("Golfer Table Added.");
            }

            conn.query(getCreateTable("COURSE")).rxExecute().doOnError(err -> {
              logger.warn("Course Table Error: {}", err.getMessage());
            }).doOnSuccess(row2 -> {
              if (!names.contains("course")) {
                logger.warn("Course Table Added.");
              }
              conn.query(getCreateTable("RATINGS")).rxExecute().doOnError(err -> {
                logger.warn("Ratings Table Error: {}", err.getMessage());
              }).doOnSuccess(row3 -> {
                if (!names.contains("ratings")) {
                  logger.warn("Ratings Table Added.");
                }
                conn.query(getCreateTable("SCORES")).rxExecute().doOnError(err -> {
                  logger.error("Scores Table Error: {}", err.getMessage());
                }).doOnSuccess(row4 -> {
                  if (!names.contains("scores")) {
                    logger.warn("Scores Table Added.");
                  }
                  conn.query(getCreateTable("GROUPS")).rxExecute().doOnError(err -> {
                    logger.error("Creating Groups Error: {}", err.getMessage());
                  }).doOnSuccess(row5 -> {
                    if (!names.contains("groups")) {
                      logger.warn("Groups Table Added.");
                    }
                    conn.query(getCreateTable("MEMBER")).rxExecute().doOnError(err -> {
                      logger.error("Member Table Error: {}", err.getMessage());
                    }).doOnSuccess(row6 -> {
                      if (!names.contains("member")) {
                        logger.warn("Member Table Added.");
                      }
                      tx.rxCommit().doOnComplete(() -> {
                        conn.rxClose().doOnComplete(() -> {
                          if (isCreateTables) {
                            returnPromise.complete(isCreateTables.toString());
                          }
                          finalPromise.complete(isCreateTables.toString());
                        }).subscribe();
                      }) .subscribe();
                    }).subscribe();
                  }).subscribe();
                }).subscribe();
              }).subscribe();
            }).subscribe();
          }).subscribe();
        })).flatMapCompletable(res -> Completable.complete())));

    completable.subscribe(() -> {
      finalPromise.future().onComplete(c -> {
        if (!isCreateTables) {
          try {
            setupSql(pool);
          } catch (SQLException e) {
            throw new RuntimeException(e);
          }
        }
      });
    }, err -> {
      logger.info("Tables Create Error: {}", err.getMessage());
      throw new RuntimeException(err);
    });
  }

  @Override
  public MessageUser createMessageUser() {
    return new MessageUserImpl();
  }

  @Override
  @SuppressWarnings("unchecked")
  public <T> T getPool() {
    return (T) pool;
  }
}
